### ISSUE TITLE
clear command report filter is not proxied

### ISSUE THREAD

**Issue by XingFang** [armon/bloomd#56]
macOS Mojave 10.14.6
bloomd v0.7.5

![image](https://user-images.githubusercontent.com/13644079/69616725-0dad5180-1072-11ea-88a1-27e7b29eed74.png)

**Comment by XingFang** [comment]
memory consumer grow up with the time, but data of several days or month be necessary,  Looking forward to a partitioning mechanism that can solve it

**Comment by armon** [comment]
@XingFang When you close the filter, it unmaps it from memory. However if you perform an operation on that in the mean time (check, set, etc) then the filter will be mapped back into memory. My guess is there is another client performing an operation between the close and clear operations, so that it is being mapped back.
